### ISSUE TITLE
Info from QtNQC’s Original Author

### ISSUE THREAD

**Issue by textbrowser** [BrickBot/QtNQC#1]
I'm the original author of QtNQC. NQC is done and abandoned. I'm working on a new project for Arduino.

https://github.com/textbrowser/glitch

**Comment by mesheets** [comment]
Hello @textbrowser , thank you for posting!  While the original NQC project might have been abandoned, a fork of the project is available within this [BrickBot organization](https://github.com/BrickBot/) at https://github.com/BrickBot/nqc.  The current NQC source code and latest release there include updates that were submitted to the original project but never incorporated there.  Any NQC-related issues, comments, pull requests, etc. are welcome to be posted there.

**Comment by mesheets** [comment]
Added info to project readme file

**Comment by textbrowser** [comment]
The yellow Lego brick is a nostalgic device. :) It has been superseded by lighter, faster, less expensive, and more capable devices. I wonder if there are any more people interested in the device.
